// Copyright 2025 Dayna Blackwell / Blackwell Systems
// SPDX-License-Identifier: Apache-2.0 OR MIT

// Package zod generates Zod validation schemas from schema IR.
package zod

import (
	"fmt"
	"strings"

	"github.com/blackwell-systems/goldenthread/internal/schema"
)

// Emitter generates Zod schemas.
type Emitter struct {
	// ImportPath is the import path for Zod (default: "zod")
	ImportPath string

	// ExportTypes controls whether to export inferred types
	ExportTypes bool
}

// NewEmitter creates a new Zod emitter with default settings.
func NewEmitter() *Emitter {
	return &Emitter{
		ImportPath:  "zod",
		ExportTypes: true,
	}
}

// Emit generates a Zod schema file from a Schema IR.
func (e *Emitter) Emit(s *schema.Schema) (string, error) {
	var b strings.Builder

	// Source origin comment (separate from docs)
	b.WriteString(fmt.Sprintf("// Generated by goldenthread from %s:%d\n", s.Pos.File, s.Pos.Line))
	b.WriteString("// DO NOT EDIT - Changes will be overwritten\n\n")

	// Import
	b.WriteString(fmt.Sprintf("import { z } from '%s'\n\n", e.ImportPath))

	// Schema documentation
	writeJSDoc(&b, "", s.Documentation)

	// Schema constant
	b.WriteString(fmt.Sprintf("export const %sSchema = z.object({\n", s.Name))

	// Filter out embedded fields (they've been flattened)
	regularFields := make([]schema.Field, 0, len(s.Fields))
	for _, field := range s.Fields {
		if !field.Embedded {
			regularFields = append(regularFields, field)
		}
	}

	for i, field := range regularFields {
		e.emitField(&b, field, i == len(regularFields)-1)
	}

	b.WriteString("})\n\n")

	// Inferred type
	if e.ExportTypes {
		b.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %sSchema>\n", s.Name, s.Name))
	}

	return b.String(), nil
}

// emitField generates a Zod field definition.
func (e *Emitter) emitField(b *strings.Builder, field schema.Field, isLast bool) {
	fieldName := field.JSONName
	if fieldName == "" {
		fieldName = camelCase(field.GoName)
	}

	// Field documentation
	writeJSDoc(b, "  ", field.Documentation)

	// Field definition
	b.WriteString(fmt.Sprintf("  %s: ", fieldName))
	e.emitType(b, field.Type, field.Rules, !field.Optional)

	if !isLast {
		b.WriteString(",")
	}
	b.WriteString("\n")
}

// emitType generates a Zod type with validation rules.
func (e *Emitter) emitType(b *strings.Builder, fieldType schema.Type, rules schema.FieldRules, required bool) {
	switch fieldType.Kind {
	case schema.TypeString:
		// Handle enum specially - it's a top-level constructor
		if rules.Enum != nil && len(rules.Enum) > 0 {
			b.WriteString("z.enum([")
			for i, val := range rules.Enum {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString("'" + val + "'")
			}
			b.WriteString("])")
			return
		}
		b.WriteString("z.string()")
		e.emitStringRules(b, rules)

	case schema.TypeInt, schema.TypeUint, schema.TypeFloat:
		b.WriteString("z.number()")
		e.emitNumericRules(b, rules)

	case schema.TypeBool:
		b.WriteString("z.boolean()")

	case schema.TypeArray:
		b.WriteString("z.array(")
		if fieldType.Elem != nil {
			e.emitType(b, *fieldType.Elem, schema.FieldRules{}, true)
		} else {
			b.WriteString("z.any()")
		}
		b.WriteString(")")
		e.emitArrayRules(b, rules)

	case schema.TypeMap:
		b.WriteString("z.record(")
		// Emit key type (Zod record requires string keys)
		if fieldType.Key != nil && fieldType.Key.Kind == schema.TypeString {
			b.WriteString("z.string(), ")
		} else if fieldType.Key != nil {
			// Non-string keys - emit anyway but note limitation
			e.emitType(b, *fieldType.Key, schema.FieldRules{}, true)
			b.WriteString(", ")
		} else {
			b.WriteString("z.string(), ")
		}
		// Emit value type
		if fieldType.Value != nil {
			e.emitType(b, *fieldType.Value, schema.FieldRules{}, true)
		} else {
			b.WriteString("z.any()")
		}
		b.WriteString(")")

	case schema.TypeObject:
		b.WriteString("z.object({\n")
		for i, prop := range fieldType.Fields {
			e.emitField(b, prop, i == len(fieldType.Fields)-1)
		}
		b.WriteString("  })")

	case schema.TypeNamed:
		if fieldType.Ref != nil {
			b.WriteString(fieldType.Ref.Name + "Schema")
		} else {
			b.WriteString("z.any()")
		}

	case schema.TypeTime:
		b.WriteString("z.string().datetime()")

	case schema.TypeUUID:
		b.WriteString("z.string().uuid()")

	default:
		b.WriteString("z.any()")
	}

	// Make optional if not required
	if !required {
		b.WriteString(".optional()")
	}
}

// emitStringRules adds string validation rules.
func (e *Emitter) emitStringRules(b *strings.Builder, rules schema.FieldRules) {
	if rules.MinLength != nil {
		b.WriteString(fmt.Sprintf(".min(%d)", *rules.MinLength))
	}
	if rules.MaxLength != nil {
		b.WriteString(fmt.Sprintf(".max(%d)", *rules.MaxLength))
	}
	if rules.Pattern != nil {
		// Escape special characters for JavaScript regex literal
		pattern := *rules.Pattern
		pattern = strings.ReplaceAll(pattern, "\\", "\\\\") // Backslash must be first
		pattern = strings.ReplaceAll(pattern, "/", "\\/")   // Forward slash (regex delimiter)
		pattern = strings.ReplaceAll(pattern, "\n", "\\n")  // Newline
		pattern = strings.ReplaceAll(pattern, "\r", "\\r")  // Carriage return
		pattern = strings.ReplaceAll(pattern, "\t", "\\t")  // Tab
		b.WriteString(fmt.Sprintf(".regex(/%s/)", pattern))
	}
	if rules.Format != nil {
		switch *rules.Format {
		case schema.FormatEmail:
			b.WriteString(".email()")
		case schema.FormatURL:
			b.WriteString(".url()")
		case schema.FormatUUID:
			b.WriteString(".uuid()")
		case schema.FormatDate:
			// ISO 8601 date format: YYYY-MM-DD
			b.WriteString(".regex(/^\\\\d{4}-\\\\d{2}-\\\\d{2}$/)")
		case schema.FormatDateTime:
			b.WriteString(".datetime()")
		case schema.FormatIPv4:
			b.WriteString(".ip({ version: 'v4' })")
		case schema.FormatIPv6:
			b.WriteString(".ip({ version: 'v6' })")
		}
	}
}

// emitNumericRules adds numeric validation rules.
func (e *Emitter) emitNumericRules(b *strings.Builder, rules schema.FieldRules) {
	if rules.Min != nil {
		b.WriteString(fmt.Sprintf(".min(%g)", *rules.Min))
	}
	if rules.Max != nil {
		b.WriteString(fmt.Sprintf(".max(%g)", *rules.Max))
	}
}

// emitArrayRules adds array validation rules.
func (e *Emitter) emitArrayRules(b *strings.Builder, rules schema.FieldRules) {
	if rules.MinItems != nil {
		b.WriteString(fmt.Sprintf(".min(%d)", *rules.MinItems))
	}
	if rules.MaxItems != nil {
		b.WriteString(fmt.Sprintf(".max(%d)", *rules.MaxItems))
	}
}

// camelCase converts PascalCase to camelCase.
func camelCase(s string) string {
	if s == "" {
		return ""
	}
	// Handle UTF-8 properly - convert first rune to lowercase
	runes := []rune(s)
	if len(runes) > 0 {
		runes[0] = []rune(strings.ToLower(string(runes[0])))[0]
	}
	return string(runes)
}

// writeJSDoc writes a JSDoc comment block with proper escaping.
func writeJSDoc(b *strings.Builder, indent string, doc string) {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return
	}

	// Escape */ to prevent breaking the comment block
	doc = strings.ReplaceAll(doc, "*/", "*\\/")

	b.WriteString(indent + "/**\n")
	for _, line := range strings.Split(doc, "\n") {
		line = strings.TrimRight(line, " \t")
		b.WriteString(indent + " * " + line + "\n")
	}
	b.WriteString(indent + " */\n")
}
