// Copyright 2025 Dayna Blackwell / Blackwell Systems
// SPDX-License-Identifier: Apache-2.0 OR MIT

// Package zod generates Zod validation schemas from schema IR.
package zod

import (
	"fmt"
	"strings"

	"github.com/blackwell-systems/goldenthread/internal/schema"
)

// Emitter generates Zod schemas.
type Emitter struct {
	// ImportPath is the import path for Zod (default: "zod")
	ImportPath string

	// ExportTypes controls whether to export inferred types
	ExportTypes bool
}

// NewEmitter creates a new Zod emitter with default settings.
func NewEmitter() *Emitter {
	return &Emitter{
		ImportPath:  "zod",
		ExportTypes: true,
	}
}

// Emit generates a Zod schema file from a Schema IR.
func (e *Emitter) Emit(s *schema.Schema) (string, error) {
	var b strings.Builder

	// Header comment
	b.WriteString(fmt.Sprintf("// Generated by goldenthread from %s:%d\n", s.Pos.File, s.Pos.Line))
	b.WriteString("// DO NOT EDIT - Changes will be overwritten\n\n")

	// Import
	b.WriteString(fmt.Sprintf("import { z } from '%s'\n\n", e.ImportPath))

	// Documentation
	if s.Documentation != "" {
		b.WriteString("/**\n")
		for _, line := range strings.Split(strings.TrimSpace(s.Documentation), "\n") {
			b.WriteString(" * " + line + "\n")
		}
		b.WriteString(" */\n")
	}

	// Schema constant
	b.WriteString(fmt.Sprintf("export const %sSchema = z.object({\n", s.Name))

	for i, field := range s.Fields {
		e.emitField(&b, field, i == len(s.Fields)-1)
	}

	b.WriteString("})\n\n")

	// Inferred type
	if e.ExportTypes {
		b.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %sSchema>\n", s.Name, s.Name))
	}

	return b.String(), nil
}

// emitField generates a Zod field definition.
func (e *Emitter) emitField(b *strings.Builder, field schema.Field, isLast bool) {
	fieldName := field.JSONName
	if fieldName == "" {
		fieldName = camelCase(field.GoName)
	}

	// Field documentation
	if field.Documentation != "" {
		b.WriteString("  /**\n")
		for _, line := range strings.Split(strings.TrimSpace(field.Documentation), "\n") {
			b.WriteString("   * " + line + "\n")
		}
		b.WriteString("   */\n")
	}

	// Field definition
	b.WriteString(fmt.Sprintf("  %s: ", fieldName))
	e.emitType(b, field.Type, field.Rules, !field.Optional)

	if !isLast {
		b.WriteString(",")
	}
	b.WriteString("\n")
}

// emitType generates a Zod type with validation rules.
func (e *Emitter) emitType(b *strings.Builder, fieldType schema.Type, rules schema.FieldRules, required bool) {
	switch fieldType.Kind {
	case schema.TypeString:
		b.WriteString("z.string()")
		e.emitStringRules(b, rules)

	case schema.TypeInt, schema.TypeUint, schema.TypeFloat:
		b.WriteString("z.number()")
		e.emitNumericRules(b, rules)

	case schema.TypeBool:
		b.WriteString("z.boolean()")

	case schema.TypeArray:
		b.WriteString("z.array(")
		if fieldType.Elem != nil {
			e.emitType(b, *fieldType.Elem, schema.FieldRules{}, true)
		} else {
			b.WriteString("z.any()")
		}
		b.WriteString(")")
		e.emitArrayRules(b, rules)

	case schema.TypeObject:
		b.WriteString("z.object({\n")
		for i, prop := range fieldType.Fields {
			e.emitField(b, prop, i == len(fieldType.Fields)-1)
		}
		b.WriteString("  })")

	case schema.TypeNamed:
		if fieldType.Ref != nil {
			b.WriteString(fieldType.Ref.Name + "Schema")
		} else {
			b.WriteString("z.any()")
		}

	case schema.TypeTime:
		b.WriteString("z.string().datetime()")

	case schema.TypeUUID:
		b.WriteString("z.string().uuid()")

	default:
		b.WriteString("z.any()")
	}

	// Make optional if not required
	if !required {
		b.WriteString(".optional()")
	}
}

// emitStringRules adds string validation rules.
func (e *Emitter) emitStringRules(b *strings.Builder, rules schema.FieldRules) {
	if rules.MinLength != nil {
		b.WriteString(fmt.Sprintf(".min(%d)", *rules.MinLength))
	}
	if rules.MaxLength != nil {
		b.WriteString(fmt.Sprintf(".max(%d)", *rules.MaxLength))
	}
	if rules.Pattern != nil {
		// Escape backslashes for TypeScript
		pattern := strings.ReplaceAll(*rules.Pattern, "\\", "\\\\")
		b.WriteString(fmt.Sprintf(".regex(/%s/)", pattern))
	}
	if rules.Enum != nil && len(rules.Enum) > 0 {
		b.WriteString(".enum([")
		for i, val := range rules.Enum {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString("'" + val + "'")
		}
		b.WriteString("])")
	}
	if rules.Format != nil {
		switch *rules.Format {
		case schema.FormatEmail:
			b.WriteString(".email()")
		case schema.FormatURL:
			b.WriteString(".url()")
		case schema.FormatUUID:
			b.WriteString(".uuid()")
		case schema.FormatDate:
			b.WriteString(".date()")
		case schema.FormatDateTime:
			b.WriteString(".datetime()")
		case schema.FormatIPv4:
			b.WriteString(".ip({ version: 'v4' })")
		case schema.FormatIPv6:
			b.WriteString(".ip({ version: 'v6' })")
		}
	}
}

// emitNumericRules adds numeric validation rules.
func (e *Emitter) emitNumericRules(b *strings.Builder, rules schema.FieldRules) {
	if rules.Min != nil {
		b.WriteString(fmt.Sprintf(".min(%g)", *rules.Min))
	}
	if rules.Max != nil {
		b.WriteString(fmt.Sprintf(".max(%g)", *rules.Max))
	}
}

// emitArrayRules adds array validation rules.
func (e *Emitter) emitArrayRules(b *strings.Builder, rules schema.FieldRules) {
	if rules.MinItems != nil {
		b.WriteString(fmt.Sprintf(".min(%d)", *rules.MinItems))
	}
	if rules.MaxItems != nil {
		b.WriteString(fmt.Sprintf(".max(%d)", *rules.MaxItems))
	}
}

// camelCase converts PascalCase to camelCase.
func camelCase(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}
